RANDOM_SEED = 42

NUM_PRODUCTS = 30
NUM_UNIQUE_SUPPLIERS = 30
NUM_WAREHOUSES = 30
NUM_STORES = 30
NUM_PURCHASE_ORDERS = 30

PRODUCT_PREFIX = "PROD"
PRODUCT_SYS_PREFIX = "SYSP"
STORE_PREFIX = "STR"
WAREHOUSE_PREFIX = "WH"