RANDOM_SEED = 42

NUM_PRODUCTS = 500
NUM_UNIQUE_SUPPLIERS = 120
NUM_WAREHOUSES = 60
NUM_STORES = 250
NUM_PURCHASE_ORDERS = 12000

PRODUCT_PREFIX = "PROD"
PRODUCT_SYS_PREFIX = "SYSP"
STORE_PREFIX = "STR"
WAREHOUSE_PREFIX = "WH"